name: API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./api
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist
      working-directory: ./api

    - name: Generate key
      run: php artisan key:generate
      working-directory: ./api
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./api
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
      working-directory: ./api
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite_test
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
      working-directory: ./api
